### ISSUE TITLE
Test issue -- Attempt to repro #6

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/fabricbot-config#23]
This issue will be used to attempt to reproduce #6, where team member activity moves an issue back to the Needs Triage column after it's been triaged.

**Comment by jeffhandley** [comment]
The issue repro'd with the following conditions:

1. Issue did not have `untriaged` label
2. Issue was in the "Triaged" column
3. A new label was added (by a user with write permissions)

The result was:

1. The issue was removed from the "Triaged" column (and the project)
2. The issue was added to the "Needs Triage" column

**Comment by jeffhandley** [comment]
The issue also repro'd when:

1. Issue did not have `untriaged` label
2. Issue was in the "Triaged" column
3. A comment was added (by a user with write permissions)

The result was:

1. The issue was removed from the "Triaged" column (and the project)
2. The issue was added to the "Needs Triage" column

**Comment by jeffhandley** [comment]
The issue does not repro when the card was in a team member's triage column.

**Comment by jeffhandley** [comment]
a61ca53a858f9383358e03ce7f100cd8f4a43450 was committed directly to main to test a condition of only resurrecting if the actor does not have write permission.

**Comment by jeffhandley** [comment]
c477933 was committed directly to main to test a fix where the resurrection logic is removed from the "Needs Triage" task

**Comment by jeffhandley** [comment]
facb3b3cde9ccdc12135430088f5ca23bb0a9a93 was committed to main; the resurrection logic was removed from the "Needs Further Triage" task

**Comment by jeffhandley** [comment]
Testing with "Needs Further Triage" resurrection in place

**Comment by jeffhandley** [comment]
Testing with 476ed82da5b42791fb00cfda3d24c9483e295441

**Comment by jeffhandley** [comment]
Testing with [a513b20](https://github.com/dotnet/fabricbot-config/commit/a513b20675f0a34afc534b67f242b922190aa09a)

**Comment by jeffhandley** [comment]
Testing with [991280b](https://github.com/dotnet/fabricbot-config/commit/991280b41ed454e9ef5c17e265cea32b699a6d79)

**Comment by jeffhandley** [comment]
Testing with [d93009d](https://github.com/dotnet/fabricbot-config/commit/d93009d5c5eb315551907a3aa1cce1e2589697d4)

**Comment by jeffhandley** [comment]
Testing with [342f89f](https://github.com/dotnet/fabricbot-config/commit/342f89fd49057eb824776e1e629cd2d42a8dc999)

**Comment by jeffhandley** [comment]
👁️

**Comment by davidfowl** [comment]
Testing somthing!

**Comment by HowardvanRooijen** [comment]
Testing!

**Comment by jchannon** [comment]
Good day sir!

**Comment by filipnavara** [comment]
Hello!
