### ISSUE TITLE
Automatically remove untriaged label across all dotnet/runtime areas

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/fabricbot-config#27]
We're interested in expanding the automated removal of the `untriaged` label based on heuristics, such that the automation covers more or all of the dotnet/runtime areas (and not just the Libraries Area Pods).

For the Libraries Areas Pods, we automatically remove the `untriaged` label when any of these 4 events occurs:

1. The issue is closed
2. A milestone is applied
3. The `needs-author-action` label is applied
4. The `api-ready-for-review` label is applied

While rules 3 and 4 are somewhat subjective from area to area, rules 1 and 2 are broadly agreed upon.

@jeffschwMSFT, @marek-safar, @karelz:

1. Would you like to have the `untriaged` label automatically removed from your teams' areas when the issue is closed or a milestone is applied?
2. Are there any other conditions you'd like to trigger the removal?

**Comment by jeffschwMSFT** [comment]
+1 for less manual work.  I see the value of 1 and 2, can you explain the rationale for 3 and 4?  In the case of 4, I would hope that milestone would also be applied.

**Comment by jeffhandley** [comment]
The `needs-author-action` label means we don't have enough information from the author and we're waiting on them (or another contributor) to add more information. Until that information arrives, it's not actionable by area owners. Once a community comment comes in, the issue shows back up on our triage project boards to ensure we follow up on it. For issues of this ilk that look like potential regressions, we will also apply the current milestone to the issue to ensure follow-up during this release.

The `api-ready-for-review` label denotes a new feature, so the risk of this being a regression that needs addressed in the current release is nil. But if we haven't already applied a milestone by the time we reach that point, then that indicates we're waiting for the API Review to make a decision on the milestone. Either way, no further "triage" is required on the issue.

**Comment by jeffschwMSFT** [comment]
Thanks for the explanations, for me personally I see the value of 1 and 2 broadly across our other labels.  I am not convinced of the other uses, but they may also not be as widely used in areas for my team.  Interested in more opinions.

**Comment by jeffhandley** [comment]
_Note: we have the flexibility to apply 1+2 across all areas and keep 3+4 scoped to the Libraries Area Pods (where we're using the aforementioned issue triage boards). But I'll wait for input from others before we conclude that direction._

**Comment by marek-safar** [comment]
> Would you like to have the untriaged label automatically removed from your teams' areas when the issue is closed or a milestone is applied?

YES!

> Are there any other conditions you'd like to trigger the removal?

I cannot think of any right now but would love to see the label back when the conditions are removed.
