### ISSUE TITLE
Remove auto-assign to eerhardt column on comments

### ISSUE THREAD

**Issue by ericstj** [dotnet/fabricbot-config#56]
cc @jeffhandley @eerhardt 

Eric comments on a lot of issues to move them along but doesn't wish to be automatically treated as the triager.  Can we remove the automation for him that automatically places issues in his column when he comments on them.  @eerhardt  would you like the same thing for PRs?

**Comment by eerhardt** [comment]
> @eerhardt would you like the same thing for PRs?

If it is easy, yes.
