### ISSUE TITLE
Bot is not removing items from columns when we transfer them to another repo

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/fabricbot-config#67]
There was an issue in the runtime repo that we transferred to another repo, and the issue was still showing up in the untriaged column. Is this something that can be implemented? Is the bot able to see a notification when an issue/PR gets transferred to another repo?

Example: Msbuild issue 8319, which we transferred from runtime.

**Comment by jeffhandley** [comment]
I don't see an obvious way to respond to this via fabricbot, but I'll look into it more.

**Comment by jeffhandley** [comment]
Unfortunately, this cannot be done through FabricBot. There's no event for us to handle for issues being transferred out of a repo.
