### ISSUE TITLE
Bot not locking issues after they get closed

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/fabricbot-config#68]
We have an issue that was closed long time ago and we are still seeing constant discussion on it. It would be nice if the bot locked it immediately, and any new discussions would be opened in a new issue or in the discussions tab.

Runtime issue 80148.

**Comment by jeffhandley** [comment]
Our config is to lock issues/prs after 30 days of inactivity after closing.
https://github.com/dotnet/runtime/blob/35e72a1c8cd819caa1a2207c5aa08daa0ecd74cf/.github/fabricbot.json#L3594-L3700

For the typical case, this is proven to be the right dial setting. We can always manually lock discussions earlier than that if prudent (with a comment explaining why).
