### ISSUE TITLE
Do not add `needs-further-triage` when `untriaged` label exists

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/fabricbot-config#76]
When the `needs-author-action` label is in place and the author comments on the issue, we have a step of automation that replaces the `needs-author-action` label with the `needs-further-triage` label. As reported by @ManickaP, this does not take the `untriaged` label into account, and it can result in both `untriaged` and `needs-further-triage` being applied, which is unexpected (and noisy).

I believe the expected behavior would be:

If the `needs-author-action` label is applied and the author comments:
- If the `untriaged` label is applied, simply remove the `needs-author-action` label
- If the `untriaged` label is not applied, remove the `needs-author-action` label and add the `needs-further-triage` label

@ManickaP and @eiriktsarpalis -- do you both agree with those conditions?

**Comment by eiriktsarpalis** [comment]
Sounds reasonable to me 👍
